' ******************************************************************************
' swxJRNL.swj - journal recorded on 07/01/23 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "6_DOF_Robotics_Arm.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007680261434852829819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, -0.1996867973061735579
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, -0.2457683659152905542
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, -0.1382447058273509333
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, -0.07680261434852829472
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.05376183004396980353
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.06144209147882263855
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, -0.07680261434852829472
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, -0.07680261434852829472
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.09216313721823395089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.07680261434852829472
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.1228841829576452771
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.09216313721823395089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, -0.09984339865308677897
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.01536052286970565964
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01536052286970565964
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, -0.1612854901319094314
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, -0.0844828757833811228
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.07680261434852829472
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.03840130717426414736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03072104573941131928
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.03072104573941131928
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.04608156860911697544
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.03840130717426414736
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03072104573941131928
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01536052286970565964
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02304078430455848772
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01536052286970565964
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03072104573941131928
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.05376183004396980353
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.03072104573941131928
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007680261434852829819
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01536052286970565964
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01536052286970565964
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1075236600879396071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.1612854901319094314
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.1459249672622037752
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.1228841829576452771
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.06912235291367546663
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.05376183004396980353
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.03072104573941131928
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.02304078430455848772
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007680261434852829819

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
